name: Deploy phpDocumentor documentation

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: phpdoc
          path: .

      - name: Deploy phpDocumentor documentation
        run: |
          git config --global user.name "Martin Bélanger"
          git config --global user.email "mbbelanger@gmail.com"
          git add .
          git commit -m "Deploy phpDocumentor documentation"
          git push

